### ISSUE TITLE
 calculate_additional_buffer simplification

### ISSUE THREAD

**Issue by mbednarski** [gethiox/jack-peak-meter#1]
https://github.com/gethiox/jack-peak-meter/blob/e7f97f28a089d191cbfe53bdd0a1f09ea3b21c84/jack-peak-meter.go#L156

If you do not need to support numbers that are not power of 2, you can simplify this expression to

`1024 / frame_size `

**Comment by gethiox** [comment]
Merged into [this pull request](https://github.com/gethiox/jack-peak-meter/pull/2).
Thanks for suggestion, I appreciative that.
